const bcrypt = require('bcryptjs');
const hash = '$2a$12$QyxEIBUMpkSapkE.VFzR4Oun26iwPcq/FRNN17etwFiQ.5n46Muby';
console.log('compareSync =>', bcrypt.compareSync('password123', hash));
console.log('hash generated by hashSync =>', bcrypt.hashSync('password123', 12));
console.log('compare generated =>', bcrypt.compareSync('password123', bcrypt.hashSync('password123', 12)));
